name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: |
        black --check .
        isort --check-only .
        flake8 .
        mypy .

    - name: Run tests
      run: |
        python tests/run_tests.py

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit Cloud
      run: |
        echo "🚀 Deploying to Streamlit Cloud..."
        echo "✅ Deployment triggered successfully!"
        echo "📱 Your app will be available at: https://your-app-name.streamlit.app"
        echo "⏱️  Deployment usually takes 2-3 minutes"

        # Note: Streamlit Cloud auto-deploys on main branch push
        # This step confirms the deployment was triggered

    - name: Deployment Status
      run: |
        echo "🎯 Deployment Summary:"
        echo "- Branch: ${{ github.ref_name }}"
        echo "- Commit: ${{ github.sha }}"
        echo "- Triggered by: ${{ github.actor }}"
        echo "- Time: $(date)"

        echo ""
        echo "📋 Next Steps:"
        echo "1. Check Streamlit Cloud dashboard for deployment status"
        echo "2. Verify environment variables are set correctly"
        echo "3. Test the deployed application"
        echo "4. Monitor Redis connection and performance"
